import { createContext, useContext, useState } from 'react';
import { DATA_TRANSLATIONS } from './data_translations';

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🌿' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🌾' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी', flag: '🇮🇳' },
];

export const TRANSLATIONS = {
  en: {
    // Nav
    nav_dashboard: 'Dashboard',
    nav_farmers: 'Farmers',
    nav_calls: 'Call History',
    nav_pest: 'Pest Control',
    nav_weather: 'Weather',
    nav_schemes: 'Schemes',
    nav_market: 'Market Prices',
    // Dashboard
    dash_title: 'Dashboard',
    dash_subtitle: 'Tamil Nadu Agricultural Intelligence — Real-time overview',
    dash_total_farmers: 'Total Farmers',
    dash_calls_today: 'Calls Today',
    dash_active_alerts: 'Active Alerts',
    dash_avg_land: 'Avg Land Size',
    dash_live_calls: 'Live Call Activity',
    dash_weather_alerts: 'Active Alerts',
    dash_top_crops: 'Top Crops',
    dash_district_dist: 'District Distribution',
    dash_registered: 'Registered on platform',
    dash_ai_calls: 'Live AI voice calls',
    dash_district_alerts: 'District weather alerts',
    dash_per_farmer: 'Per registered farmer',
    // Farmers
    farmers_title: 'Farmers',
    farmers_subtitle: 'registered farmers across Tamil Nadu',
    farmers_search: 'Search by name, phone, village...',
    farmers_all_districts: 'All Districts',
    farmers_all_crops: 'All Crops',
    farmers_clear: 'Clear',
    farmers_no_found: 'No farmers found',
    farmers_no_found_sub: 'Try adjusting your search or filters',
    farmers_col_farmer: 'Farmer',
    farmers_col_village: 'Village',
    farmers_col_district: 'District',
    farmers_col_crops: 'Crops',
    farmers_col_lastcall: 'Last Call',
    farmers_col_totalcalls: 'Total Calls',
    farmers_showing: 'Showing',
    farmers_of: 'of',
    farmers_prev: 'Prev',
    farmers_next: 'Next',
    // Farmer Detail
    detail_back: 'Back to Farmers',
    detail_updated: 'Profile updated successfully',
    detail_total_calls: 'Total Calls',
    detail_alerts_sent: 'Alerts Sent',
    detail_land_size: 'Land Size',
    detail_language: 'Language',
    detail_village: 'Village',
    detail_district: 'District',
    detail_joined: 'Joined',
    detail_irrigation: 'Irrigation',
    detail_soil: 'Soil Type',
    detail_last_call: 'Last Call',
    detail_crops: 'Crops',
    detail_call_history: 'Call History',
    detail_no_calls: 'No calls yet',
    detail_pest_diagnoses: 'Pest Diagnoses',
    detail_edit: 'Edit Profile',
    detail_edit_title: 'Edit Farmer Profile',
    detail_save: 'Save Changes',
    detail_cancel: 'Cancel',
    // Calls
    calls_title: 'Call History',
    calls_subtitle: 'total calls',
    calls_completed: 'completed',
    calls_avg: 'Avg',
    calls_export: 'Export CSV',
    calls_search: 'Search farmer name or phone...',
    calls_all_districts: 'All Districts',
    calls_clear: 'Clear',
    calls_no_found: 'No calls found',
    calls_adjust: 'Adjust your search filters',
    calls_col_farmer: 'Farmer',
    calls_col_district: 'District',
    calls_col_datetime: 'Date & Time',
    calls_col_duration: 'Duration',
    calls_col_status: 'Status',
    calls_col_crops: 'Crops',
    calls_transcript: 'TRANSCRIPT SUMMARY',
    // Pest
    pest_title: 'Pest Control',
    pest_subtitle: 'AI-powered crop disease identification using Claude Vision',
    pest_upload: 'Upload Crop Image',
    pest_drag: 'Drag & drop crop photo here',
    pest_browse: 'Or click to browse · JPG, PNG, WebP',
    pest_phone: 'Farmer Phone (optional)',
    pest_save: 'Save',
    pest_analyse: 'Analyse',
    pest_analysing: 'Analyzing with AI...',
    pest_treatment: 'Treatment Steps',
    pest_prevention: 'PREVENTION TIP',
    pest_call_farmer: 'Call Farmer',
    pest_confidence: 'Confidence',
    pest_past: 'Past Diagnoses',
    pest_common: 'Common Pests Gallery',
    pest_remove: 'Remove image',
    pest_severity: 'Severity',
    // Weather
    weather_title: 'Weather Center',
    weather_subtitle: '3-day forecast for all Tamil Nadu districts',
    weather_active_alerts: 'Districts with Active Alerts',
    weather_search: 'Search district...',
    weather_alerts_only: 'Alerts Only',
    weather_max: 'Max',
    weather_min: 'Min',
    weather_rain: 'Rain',
    weather_alert_btn: 'Alert All Farmers',
    weather_alert_sent: 'Alert Sent!',
    weather_farmers: 'farmers',
    // Schemes
    schemes_title: 'Schemes & Subsidies',
    schemes_subtitle: 'government schemes for Tamil Nadu farmers',
    schemes_search: 'Search schemes...',
    schemes_clear: 'Clear',
    schemes_no_found: 'No schemes found',
    schemes_all: 'All',
    schemes_eligibility: 'Eligibility',
    schemes_district: 'Applicable District',
    schemes_land: 'Land Size',
    schemes_helpline: 'Helpline',
    schemes_how: 'How to Apply',
    schemes_mark_sent: 'Mark as Sent to Farmer',
    schemes_marked: 'Marked as Sent',
    schemes_sent_badge: 'Sent to farmer',
    schemes_apply: 'Apply Online',
    // Market
    market_title: 'Market Prices',
    market_subtitle: 'Live APMC prices across Tamil Nadu · Updated today',
    market_alert: 'crops below 30-day average',
    market_alert_sub: 'Consider delaying sale or using government MSP',
    market_search: 'Search crop...',
    market_today: 'Today',
    market_yesterday: 'Yesterday',
    market_lastweek: 'Last Week',
    market_vs_avg: 'vs 30-day Avg',
    market_trend: 'Trend',
    market_chart: 'Chart',
    market_30day: '30-day price trend',
    market_above_avg: '↑ Above avg',
    market_below_avg: '↓ Below avg',
    market_crop: 'Crop',
    // Pest extras
    pest_upload_analyse: 'Upload a crop image and click Analyse',
    pest_ai_identify: 'AI will identify diseases and suggest treatment',
    // General
    gen_live: 'Live',
    gen_no_data: 'No data',
    gen_loading: 'Loading...',
    gen_farmers_count: 'farmers',
    gen_completed: 'completed',
    gen_missed: 'missed',
    gen_high: 'High',
    gen_medium: 'Medium',
    gen_low: 'Low',
  },

  ta: {
    // Nav
    nav_dashboard: 'டாஷ்போர்டு',
    nav_farmers: 'விவசாயிகள்',
    nav_calls: 'அழைப்பு வரலாறு',
    nav_pest: 'பூச்சி கட்டுப்பாடு',
    nav_weather: 'வானிலை',
    nav_schemes: 'திட்டங்கள்',
    nav_market: 'சந்தை விலை',
    // Dashboard
    dash_title: 'டாஷ்போர்டு',
    dash_subtitle: 'தமிழ்நாடு வேளாண் நுண்ணறிவு — நிகழ்நேர மேலோட்டம்',
    dash_total_farmers: 'மொத்த விவசாயிகள்',
    dash_calls_today: 'இன்று அழைப்புகள்',
    dash_active_alerts: 'செயலில் எச்சரிக்கைகள்',
    dash_avg_land: 'சராசரி நில அளவு',
    dash_live_calls: 'நிகழ்நேர அழைப்பு செயல்பாடு',
    dash_weather_alerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    dash_top_crops: 'முக்கிய பயிர்கள்',
    dash_district_dist: 'மாவட்ட பரவல்',
    dash_registered: 'பதிவுசெய்யப்பட்ட விவசாயிகள்',
    dash_ai_calls: 'செயற்கை நுண்ணறிவு குரல் அழைப்புகள்',
    dash_district_alerts: 'மாவட்ட வானிலை எச்சரிக்கைகள்',
    dash_per_farmer: 'ஒரு விவசாயிக்கு சராசரி',
    // Farmers
    farmers_title: 'விவசாயிகள்',
    farmers_subtitle: 'தமிழ்நாட்டில் பதிவுசெய்யப்பட்ட விவசாயிகள்',
    farmers_search: 'பெயர், தொலைபேசி, கிராமம் தேடுக...',
    farmers_all_districts: 'அனைத்து மாவட்டங்கள்',
    farmers_all_crops: 'அனைத்து பயிர்கள்',
    farmers_clear: 'அழி',
    farmers_no_found: 'விவசாயிகள் கிடைக்கவில்லை',
    farmers_no_found_sub: 'தேடலை மாற்றி முயற்சிக்கவும்',
    farmers_col_farmer: 'விவசாயி',
    farmers_col_village: 'கிராமம்',
    farmers_col_district: 'மாவட்டம்',
    farmers_col_crops: 'பயிர்கள்',
    farmers_col_lastcall: 'கடைசி அழைப்பு',
    farmers_col_totalcalls: 'மொத்த அழைப்புகள்',
    farmers_showing: 'காட்டுகிறது',
    farmers_of: 'இல்',
    farmers_prev: 'முந்தைய',
    farmers_next: 'அடுத்து',
    // Farmer Detail
    detail_back: 'விவசாயிகளுக்கு திரும்பு',
    detail_updated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    detail_total_calls: 'மொத்த அழைப்புகள்',
    detail_alerts_sent: 'அனுப்பப்பட்ட எச்சரிக்கைகள்',
    detail_land_size: 'நில அளவு',
    detail_language: 'மொழி',
    detail_village: 'கிராமம்',
    detail_district: 'மாவட்டம்',
    detail_joined: 'சேர்ந்த தேதி',
    detail_irrigation: 'நீர்ப்பாசனம்',
    detail_soil: 'மண் வகை',
    detail_last_call: 'கடைசி அழைப்பு',
    detail_crops: 'பயிர்கள்',
    detail_call_history: 'அழைப்பு வரலாறு',
    detail_no_calls: 'இன்னும் அழைப்புகள் இல்லை',
    detail_pest_diagnoses: 'பூச்சி அடையாளம்',
    detail_edit: 'சுயவிவரம் திருத்து',
    detail_edit_title: 'விவசாயி சுயவிவரம் திருத்து',
    detail_save: 'மாற்றங்களை சேமி',
    detail_cancel: 'ரத்துசெய்',
    // Calls
    calls_title: 'அழைப்பு வரலாறு',
    calls_subtitle: 'மொத்த அழைப்புகள்',
    calls_completed: 'முடிந்தது',
    calls_avg: 'சராசரி',
    calls_export: 'CSV இறக்குமதி',
    calls_search: 'விவசாயி பெயர் அல்லது தொலைபேசி தேடுக...',
    calls_all_districts: 'அனைத்து மாவட்டங்கள்',
    calls_clear: 'அழி',
    calls_no_found: 'அழைப்புகள் கிடைக்கவில்லை',
    calls_adjust: 'தேடல் வடிகட்டிகளை சரிசெய்யவும்',
    calls_col_farmer: 'விவசாயி',
    calls_col_district: 'மாவட்டம்',
    calls_col_datetime: 'தேதி & நேரம்',
    calls_col_duration: 'கால அளவு',
    calls_col_status: 'நிலை',
    calls_col_crops: 'பயிர்கள்',
    calls_transcript: 'உரையாடல் சுருக்கம்',
    // Pest
    pest_title: 'பூச்சி கட்டுப்பாடு',
    pest_subtitle: 'கிளாட் விஷன் மூலம் செயற்கை நுண்ணறிவு பயிர் நோய் கண்டுபிடிப்பு',
    pest_upload: 'பயிர் படம் பதிவேற்றுக',
    pest_drag: 'பயிர் நோய் படத்தை இங்கே இழுத்து விடவும்',
    pest_browse: 'அல்லது கணினியிலிருந்து தேர்வு செய்க · JPG, PNG, WebP',
    pest_phone: 'விவசாயி தொலைபேசி (விருப்பமானது)',
    pest_save: 'சேமி',
    pest_analyse: 'பகுப்பாய்வு',
    pest_analysing: 'செயற்கை நுண்ணறிவால் பகுப்பாய்வு செய்கிறது...',
    pest_treatment: 'சிகிச்சை படிகள்',
    pest_prevention: 'தடுப்பு குறிப்பு',
    pest_call_farmer: 'விவசாயியை அழைக்கவும்',
    pest_confidence: 'நம்பகத்தன்மை',
    pest_past: 'கடந்த கால கண்டறிதல்',
    pest_common: 'பொதுவான பூச்சிகள் காட்சியகம்',
    pest_remove: 'படத்தை நீக்கு',
    pest_severity: 'தீவிரம்',
    // Weather
    weather_title: 'வானிலை மையம்',
    weather_subtitle: 'தமிழ்நாட்டின் அனைத்து மாவட்டங்களுக்கும் 3-நாள் வானிலை',
    weather_active_alerts: 'எச்சரிக்கை உள்ள மாவட்டங்கள்',
    weather_search: 'மாவட்டம் தேடுக...',
    weather_alerts_only: 'எச்சரிக்கை மட்டும்',
    weather_max: 'அதிகபட்சம்',
    weather_min: 'குறைந்தது',
    weather_rain: 'மழை',
    weather_alert_btn: 'அனைத்து விவசாயிகளுக்கும் எச்சரிக்கை',
    weather_alert_sent: 'எச்சரிக்கை அனுப்பப்பட்டது!',
    weather_farmers: 'விவசாயிகள்',
    // Schemes
    schemes_title: 'திட்டங்கள் & மானியங்கள்',
    schemes_subtitle: 'தமிழ்நாடு விவசாயிகளுக்கான அரசு திட்டங்கள்',
    schemes_search: 'திட்டங்கள் தேடுக...',
    schemes_clear: 'அழி',
    schemes_no_found: 'திட்டங்கள் கிடைக்கவில்லை',
    schemes_all: 'அனைத்தும்',
    schemes_eligibility: 'தகுதி',
    schemes_district: 'பொருந்தும் மாவட்டம்',
    schemes_land: 'நில அளவு',
    schemes_helpline: 'உதவி எண்',
    schemes_how: 'விண்ணப்பிப்பது எப்படி',
    schemes_mark_sent: 'விவசாயிக்கு அனுப்பியதாக குறி',
    schemes_marked: 'அனுப்பியதாக குறிக்கப்பட்டது',
    schemes_apply: 'ஆன்லைன் விண்ணப்பிக்க',
    // Market
    market_title: 'சந்தை விலை',
    market_subtitle: 'தமிழ்நாடு முழுவதும் நேரடி APMC விலைகள் · இன்று புதுப்பிக்கப்பட்டது',
    market_alert: 'பயிர்கள் 30-நாள் சராசரிக்கும் கீழே',
    market_alert_sub: 'விற்பனையை தாமதிக்கவும் அல்லது அரசு MSP பயன்படுத்தவும்',
    market_search: 'பயிர் தேடுக...',
    market_today: 'இன்று',
    market_yesterday: 'நேற்று',
    market_lastweek: 'கடந்த வாரம்',
    market_vs_avg: '30-நாள் சராசரி',
    market_trend: 'போக்கு',
    market_chart: 'விளக்கப்படம்',
    market_30day: '30-நாள் விலை போக்கு',
    market_above_avg: '↑ சராசரிக்கு மேல்',
    market_below_avg: '↓ சராசரிக்கு கீழே',
    market_crop: 'பயிர்',
    // Pest extras
    pest_upload_analyse: 'பயிர் படம் பதிவேற்றி பகுப்பாய்வு செய்யவும்',
    pest_ai_identify: 'செயற்கை நுண்ணறிவு நோய்களை கண்டுபிடிக்கும்',
    // General
    gen_live: 'நேரடி',
    gen_no_data: 'தரவு இல்லை',
    gen_loading: 'ஏற்றுகிறது...',
    gen_farmers_count: 'விவசாயிகள்',
    gen_completed: 'முடிந்தது',
    gen_missed: 'தவறுவிட்டது',
    gen_high: 'அதிகம்',
    gen_medium: 'நடுத்தரம்',
    gen_low: 'குறைவு',
  },

  te: {
    // Nav
    nav_dashboard: 'డాష్‌బోర్డ్',
    nav_farmers: 'రైతులు',
    nav_calls: 'కాల్ చరిత్ర',
    nav_pest: 'పురుగు నియంత్రణ',
    nav_weather: 'వాతావరణం',
    nav_schemes: 'పథకాలు',
    nav_market: 'మార్కెట్ ధరలు',
    // Dashboard
    dash_title: 'డాష్‌బోర్డ్',
    dash_subtitle: 'తమిళనాడు వ్యవసాయ నుండి రియల్-టైమ్ అవలోకనం',
    dash_total_farmers: 'మొత్తం రైతులు',
    dash_calls_today: 'ఈరోజు కాల్స్',
    dash_active_alerts: 'క్రియాశీల హెచ్చరికలు',
    dash_avg_land: 'సగటు భూమి పరిమాణం',
    dash_live_calls: 'లైవ్ కాల్ కార్యకలాపం',
    dash_weather_alerts: 'క్రియాశీల హెచ్చరికలు',
    dash_top_crops: 'టాప్ పంటలు',
    dash_district_dist: 'జిల్లా పంపిణీ',
    dash_registered: 'నమోదు చేసిన రైతులు',
    dash_ai_calls: 'AI వాయిస్ కాల్స్',
    dash_district_alerts: 'జిల్లా వాతావరణ హెచ్చరికలు',
    dash_per_farmer: 'ప్రతి రైతుకు',
    // Farmers
    farmers_title: 'రైతులు',
    farmers_subtitle: 'తమిళనాడులో నమోదు చేసిన రైతులు',
    farmers_search: 'పేరు, ఫోన్, గ్రామం వెతకండి...',
    farmers_all_districts: 'అన్ని జిల్లాలు',
    farmers_all_crops: 'అన్ని పంటలు',
    farmers_clear: 'తొలగించు',
    farmers_no_found: 'రైతులు కనుగొనబడలేదు',
    farmers_no_found_sub: 'శోధనను మార్చి ప్రయత్నించండి',
    farmers_col_farmer: 'రైతు',
    farmers_col_village: 'గ్రామం',
    farmers_col_district: 'జిల్లా',
    farmers_col_crops: 'పంటలు',
    farmers_col_lastcall: 'చివరి కాల్',
    farmers_col_totalcalls: 'మొత్తం కాల్స్',
    farmers_showing: 'చూపిస్తున్నది',
    farmers_of: 'లో',
    farmers_prev: 'మునుపు',
    farmers_next: 'తరువాత',
    // Farmer Detail
    detail_back: 'రైతులకు తిరిగి',
    detail_updated: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది',
    detail_total_calls: 'మొత్తం కాల్స్',
    detail_alerts_sent: 'హెచ్చరికలు పంపబడ్డాయి',
    detail_land_size: 'భూమి పరిమాణం',
    detail_language: 'భాష',
    detail_village: 'గ్రామం',
    detail_district: 'జిల్లా',
    detail_joined: 'చేరిన తేదీ',
    detail_irrigation: 'నీటిపారుదల',
    detail_soil: 'మట్టి రకం',
    detail_last_call: 'చివరి కాల్',
    detail_crops: 'పంటలు',
    detail_call_history: 'కాల్ చరిత్ర',
    detail_no_calls: 'ఇంకా కాల్స్ లేవు',
    detail_pest_diagnoses: 'పురుగు నిర్ధారణలు',
    detail_edit: 'ప్రొఫైల్ సవరించు',
    detail_edit_title: 'రైతు ప్రొఫైల్ సవరించు',
    detail_save: 'మార్పులు సేవ్ చేయి',
    detail_cancel: 'రద్దు',
    // Calls
    calls_title: 'కాల్ చరిత్ర',
    calls_subtitle: 'మొత్తం కాల్స్',
    calls_completed: 'పూర్తి అయింది',
    calls_avg: 'సగటు',
    calls_export: 'CSV ఎగుమతి',
    calls_search: 'రైతు పేరు లేదా ఫోన్ వెతకండి...',
    calls_all_districts: 'అన్ని జిల్లాలు',
    calls_clear: 'తొలగించు',
    calls_no_found: 'కాల్స్ కనుగొనబడలేదు',
    calls_adjust: 'శోధన ఫిల్టర్లు సర్దుబాటు చేయండి',
    calls_col_farmer: 'రైతు',
    calls_col_district: 'జిల్లా',
    calls_col_datetime: 'తేదీ & సమయం',
    calls_col_duration: 'వ్యవధి',
    calls_col_status: 'స్థితి',
    calls_col_crops: 'పంటలు',
    calls_transcript: 'సంభాషణ సారాంశం',
    // Pest
    pest_title: 'పురుగు నియంత్రణ',
    pest_subtitle: 'Claude Vision ద్వారా AI పంట వ్యాధి గుర్తింపు',
    pest_upload: 'పంట చిత్రం అప్‌లోడ్ చేయి',
    pest_drag: 'పంట ఫోటోని ఇక్కడ లాగి వదలండి',
    pest_browse: 'లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి · JPG, PNG, WebP',
    pest_phone: 'రైతు ఫోన్ (ఐచ్ఛికం)',
    pest_save: 'సేవ్',
    pest_analyse: 'విశ్లేషించు',
    pest_analysing: 'AI తో విశ్లేషిస్తున్నది...',
    pest_treatment: 'చికిత్స దశలు',
    pest_prevention: 'నివారణ చిట్కా',
    pest_call_farmer: 'రైతుకు కాల్ చేయి',
    pest_confidence: 'నమ్మకం',
    pest_past: 'గత నిర్ధారణలు',
    pest_common: 'సాధారణ పురుగుల గ్యాలరీ',
    pest_remove: 'చిత్రం తొలగించు',
    pest_severity: 'తీవ్రత',
    // Weather
    weather_title: 'వాతావరణ కేంద్రం',
    weather_subtitle: 'తమిళనాడు జిల్లాలకు 3-రోజుల వాతావరణ అంచనా',
    weather_active_alerts: 'క్రియాశీల హెచ్చరికలు ఉన్న జిల్లాలు',
    weather_search: 'జిల్లా వెతకండి...',
    weather_alerts_only: 'హెచ్చరికలు మాత్రమే',
    weather_max: 'గరిష్ట',
    weather_min: 'కనిష్ట',
    weather_rain: 'వర్షం',
    weather_alert_btn: 'అన్ని రైతులకు హెచ్చరించు',
    weather_alert_sent: 'హెచ్చరిక పంపబడింది!',
    weather_farmers: 'రైతులు',
    // Schemes
    schemes_title: 'పథకాలు & సబ్సిడీలు',
    schemes_subtitle: 'తమిళనాడు రైతులకు ప్రభుత్వ పథకాలు',
    schemes_search: 'పథకాలు వెతకండి...',
    schemes_clear: 'తొలగించు',
    schemes_no_found: 'పథకాలు కనుగొనబడలేదు',
    schemes_all: 'అన్నీ',
    schemes_eligibility: 'అర్హత',
    schemes_district: 'వర్తించే జిల్లా',
    schemes_land: 'భూమి పరిమాణం',
    schemes_helpline: 'హెల్ప్‌లైన్',
    schemes_how: 'దరఖాస్తు చేయడం ఎలా',
    schemes_mark_sent: 'రైతుకు పంపినట్లు గుర్తించు',
    schemes_marked: 'పంపినట్లు గుర్తించబడింది',
    schemes_apply: 'ఆన్‌లైన్లో దరఖాస్తు చేయి',
    // Market
    market_title: 'మార్కెట్ ధరలు',
    market_subtitle: 'తమిళనాడులో లైవ్ APMC ధరలు · ఈరోజు నవీకరించబడింది',
    market_alert: 'పంటలు 30-రోజుల సగటు కంటే తక్కువ',
    market_alert_sub: 'అమ్మకాన్ని వాయిదా వేయండి లేదా ప్రభుత్వ MSP ఉపయోగించండి',
    market_search: 'పంట వెతకండి...',
    market_today: 'ఈరోజు',
    market_yesterday: 'నిన్న',
    market_lastweek: 'గత వారం',
    market_vs_avg: '30-రోజుల సగటు',
    market_trend: 'ట్రెండ్',
    market_chart: 'చార్ట్',
    market_30day: '30-రోజుల ధర ట్రెండ్',
    market_above_avg: '↑ సగటు పైన',
    market_below_avg: '↓ సగటు కింద',
    market_crop: 'పంట',
    // Pest extras
    pest_upload_analyse: 'పంట చిత్రం అప్‌లోడ్ చేసి విశ్లేషించండి',
    pest_ai_identify: 'AI వ్యాధులను గుర్తించి చికిత్స సూచిస్తుంది',
    // General
    gen_live: 'లైవ్',
    gen_no_data: 'డేటా లేదు',
    gen_loading: 'లోడ్ అవుతున్నది...',
    gen_farmers_count: 'రైతులు',
    gen_completed: 'పూర్తి',
    gen_missed: 'మిస్',
    gen_high: 'అధికం',
    gen_medium: 'మధ్యస్థం',
    gen_low: 'తక్కువ',
  },

  hi: {
    // Nav
    nav_dashboard: 'डैशबोर्ड',
    nav_farmers: 'किसान',
    nav_calls: 'कॉल इतिहास',
    nav_pest: 'पेस्ट नियंत्रण',
    nav_weather: 'मौसम',
    nav_schemes: 'योजनाएं',
    nav_market: 'बाजार भाव',
    // Dashboard
    dash_title: 'डैशबोर्ड',
    dash_subtitle: 'तमिलनाडु कृषि बुद्धिमत्ता — रियल-टाइम अवलोकन',
    dash_total_farmers: 'कुल किसान',
    dash_calls_today: 'आज के कॉल',
    dash_active_alerts: 'सक्रिय अलर्ट',
    dash_avg_land: 'औसत भूमि आकार',
    dash_live_calls: 'लाइव कॉल गतिविधि',
    dash_weather_alerts: 'सक्रिय अलर्ट',
    dash_top_crops: 'शीर्ष फसलें',
    dash_district_dist: 'जिला वितरण',
    dash_registered: 'पंजीकृत किसान',
    dash_ai_calls: 'AI वॉइस कॉल',
    dash_district_alerts: 'जिला मौसम अलर्ट',
    dash_per_farmer: 'प्रति किसान',
    // Farmers
    farmers_title: 'किसान',
    farmers_subtitle: 'तमिलनाडु में पंजीकृत किसान',
    farmers_search: 'नाम, फोन, गाँव खोजें...',
    farmers_all_districts: 'सभी जिले',
    farmers_all_crops: 'सभी फसलें',
    farmers_clear: 'साफ करें',
    farmers_no_found: 'किसान नहीं मिले',
    farmers_no_found_sub: 'खोज बदलकर प्रयास करें',
    farmers_col_farmer: 'किसान',
    farmers_col_village: 'गाँव',
    farmers_col_district: 'जिला',
    farmers_col_crops: 'फसलें',
    farmers_col_lastcall: 'अंतिम कॉल',
    farmers_col_totalcalls: 'कुल कॉल',
    farmers_showing: 'दिखा रहा है',
    farmers_of: 'में से',
    farmers_prev: 'पिछला',
    farmers_next: 'अगला',
    // Farmer Detail
    detail_back: 'किसानों पर वापस',
    detail_updated: 'प्रोफाइल सफलतापूर्वक अपडेट हुई',
    detail_total_calls: 'कुल कॉल',
    detail_alerts_sent: 'भेजे गए अलर्ट',
    detail_land_size: 'भूमि आकार',
    detail_language: 'भाषा',
    detail_village: 'गाँव',
    detail_district: 'जिला',
    detail_joined: 'जुड़ने की तारीख',
    detail_irrigation: 'सिंचाई',
    detail_soil: 'मिट्टी का प्रकार',
    detail_last_call: 'अंतिम कॉल',
    detail_crops: 'फसलें',
    detail_call_history: 'कॉल इतिहास',
    detail_no_calls: 'अभी तक कॉल नहीं',
    detail_pest_diagnoses: 'कीट निदान',
    detail_edit: 'प्रोफाइल संपादित करें',
    detail_edit_title: 'किसान प्रोफाइल संपादित करें',
    detail_save: 'परिवर्तन सहेजें',
    detail_cancel: 'रद्द करें',
    // Calls
    calls_title: 'कॉल इतिहास',
    calls_subtitle: 'कुल कॉल',
    calls_completed: 'पूर्ण',
    calls_avg: 'औसत',
    calls_export: 'CSV निर्यात',
    calls_search: 'किसान का नाम या फोन खोजें...',
    calls_all_districts: 'सभी जिले',
    calls_clear: 'साफ करें',
    calls_no_found: 'कॉल नहीं मिले',
    calls_adjust: 'खोज फिल्टर समायोजित करें',
    calls_col_farmer: 'किसान',
    calls_col_district: 'जिला',
    calls_col_datetime: 'तारीख और समय',
    calls_col_duration: 'अवधि',
    calls_col_status: 'स्थिति',
    calls_col_crops: 'फसलें',
    calls_transcript: 'बातचीत का सारांश',
    // Pest
    pest_title: 'पेस्ट नियंत्रण',
    pest_subtitle: 'Claude Vision द्वारा AI फसल रोग पहचान',
    pest_upload: 'फसल की छवि अपलोड करें',
    pest_drag: 'फसल की फोटो यहाँ खींचें',
    pest_browse: 'या ब्राउज़ करने के लिए क्लिक करें · JPG, PNG, WebP',
    pest_phone: 'किसान का फोन (वैकल्पिक)',
    pest_save: 'सहेजें',
    pest_analyse: 'विश्लेषण करें',
    pest_analysing: 'AI से विश्लेषण हो रहा है...',
    pest_treatment: 'उपचार के चरण',
    pest_prevention: 'रोकथाम टिप',
    pest_call_farmer: 'किसान को कॉल करें',
    pest_confidence: 'विश्वास',
    pest_past: 'पिछले निदान',
    pest_common: 'सामान्य कीट गैलरी',
    pest_remove: 'छवि हटाएं',
    pest_severity: 'गंभीरता',
    // Weather
    weather_title: 'मौसम केंद्र',
    weather_subtitle: 'तमिलनाडु के सभी जिलों के लिए 3-दिन का पूर्वानुमान',
    weather_active_alerts: 'सक्रिय अलर्ट वाले जिले',
    weather_search: 'जिला खोजें...',
    weather_alerts_only: 'केवल अलर्ट',
    weather_max: 'अधिकतम',
    weather_min: 'न्यूनतम',
    weather_rain: 'बारिश',
    weather_alert_btn: 'सभी किसानों को अलर्ट करें',
    weather_alert_sent: 'अलर्ट भेजा गया!',
    weather_farmers: 'किसान',
    // Schemes
    schemes_title: 'योजनाएं और सब्सिडी',
    schemes_subtitle: 'तमिलनाडु किसानों के लिए सरकारी योजनाएं',
    schemes_search: 'योजनाएं खोजें...',
    schemes_clear: 'साफ करें',
    schemes_no_found: 'योजनाएं नहीं मिलीं',
    schemes_all: 'सभी',
    schemes_eligibility: 'पात्रता',
    schemes_district: 'लागू जिला',
    schemes_land: 'भूमि आकार',
    schemes_helpline: 'हेल्पलाइन',
    schemes_how: 'आवेदन कैसे करें',
    schemes_mark_sent: 'किसान को भेजा गया',
    schemes_marked: 'भेजा गया चिह्नित',
    schemes_apply: 'ऑनलाइन आवेदन करें',
    // Market
    market_title: 'बाजार भाव',
    market_subtitle: 'तमिलनाडु में लाइव APMC कीमतें · आज अपडेट',
    market_alert: 'फसलें 30-दिन के औसत से नीचे',
    market_alert_sub: 'बिक्री में देरी करें या सरकारी MSP का उपयोग करें',
    market_search: 'फसल खोजें...',
    market_today: 'आज',
    market_yesterday: 'कल',
    market_lastweek: 'पिछले सप्ताह',
    market_vs_avg: '30-दिन औसत',
    market_trend: 'रुझान',
    market_chart: 'चार्ट',
    market_30day: '30-दिन का भाव रुझान',
    market_above_avg: '↑ औसत से ऊपर',
    market_below_avg: '↓ औसत से नीचे',
    market_crop: 'फसल',
    // Pest extras
    pest_upload_analyse: 'फसल की छवि अपलोड करें और विश्लेषण करें',
    pest_ai_identify: 'AI बीमारियों की पहचान करेगा',
    // General
    gen_live: 'लाइव',
    gen_no_data: 'कोई डेटा नहीं',
    gen_loading: 'लोड हो रहा है...',
    gen_farmers_count: 'किसान',
    gen_completed: 'पूर्ण',
    gen_missed: 'छूटा',
    gen_high: 'उच्च',
    gen_medium: 'मध्यम',
    gen_low: 'निम्न',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('agribot-lang') || 'en');

  const changeLang = (code) => {
    setLang(code);
    localStorage.setItem('agribot-lang', code);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;

  const tData = (str) => {
    if (!str || typeof str !== 'string') return str;
    if (lang === 'en') return str;
    const map = DATA_TRANSLATIONS[lang];
    if (!map) return str;
    // Fast path: exact match (handles 'Red Loam', 'Heavy Rain', 'Cluster Beans' etc.)
    if (map[str]) return map[str];
    // Try space-separated word-by-word (for 'Rice Blast', 'Brown Plant Hopper')
    const spaceTranslated = str.split(' ').map(w => map[w] || w).join(' ');
    if (spaceTranslated !== str) return spaceTranslated;
    // CamelCase split fallback (for 'MuruganPillai' style – rare)
    return str.replace(/([A-Z][a-z]+)/g, match => map[match] || match);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t, tData }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
